python tts.py business\specials\agents\specials.aesthetics-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.aesthetics-agent\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.agent-loop-creator\docs\user_guide.script.hk.txt -o business\specials\agents\specials.agent-loop-creator\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.agentic-rag-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.agentic-rag-agent\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.autotelic-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.autotelic-agent\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.complex-problem-solution-process-model\docs\user_guide.script.hk.txt -o business\specials\agents\specials.complex-problem-solution-process-model\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.controller-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.controller-agent\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.general-creative-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.general-creative-agent\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.intent-analysis-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.intent-analysis-agent\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.knowledge-router-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.knowledge-router-agent\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.llm-usage\docs\user_guide.script.hk.txt -o business\specials\agents\specials.llm-usage\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.optimization-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.optimization-agent\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.planner-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.planner-agent\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.podcast-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.podcast-agent\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.psychological-profile-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.psychological-profile-agent\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.psychological-recommendation-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.psychological-recommendation-agent\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.research-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.research-agent\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.screenwriter-strategic-goal-achievement-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.screenwriter-strategic-goal-achievement-agent\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.strategic-goal-achievement-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.strategic-goal-achievement-agent\docs\user_guide.script.hk.mp3
python tts.py business\specials\agents\specials.techology-advisor-agent\docs\user_guide.script.hk.txt -o business\specials\agents\specials.techology-advisor-agent\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.accessibility\docs\user_guide.script.hk.txt -o business\video\agents\video.accessibility\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.accessibilityoptimizer\docs\user_guide.script.hk.txt -o business\video\agents\video.accessibilityoptimizer\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.aiqaconsistency\docs\user_guide.script.hk.txt -o business\video\agents\video.aiqaconsistency\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.analyst\docs\user_guide.script.hk.txt -o business\video\agents\video.analyst\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.animator_2d\docs\user_guide.script.hk.txt -o business\video\agents\video.animator_2d\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.archivemaster\docs\user_guide.script.hk.txt -o business\video\agents\video.archivemaster\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.archiveproducer\docs\user_guide.script.hk.txt -o business\video\agents\video.archiveproducer\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.archiveresearch\docs\user_guide.script.hk.txt -o business\video\agents\video.archiveresearch\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.audiencesim\docs\user_guide.script.hk.txt -o business\video\agents\video.audiencesim\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.audiobooknarrator\docs\user_guide.script.hk.txt -o business\video\agents\video.audiobooknarrator\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.avatardesign\docs\user_guide.script.hk.txt -o business\video\agents\video.avatardesign\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.awardsstrategist\docs\user_guide.script.hk.txt -o business\video\agents\video.awardsstrategist\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.benchmarkresearch\docs\user_guide.script.hk.txt -o business\video\agents\video.benchmarkresearch\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.brand\docs\user_guide.script.hk.txt -o business\video\agents\video.brand\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.brandstrategist\docs\user_guide.script.hk.txt -o business\video\agents\video.brandstrategist\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.cameraoperator\docs\user_guide.script.hk.txt -o business\video\agents\video.cameraoperator\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.casting\docs\user_guide.script.hk.txt -o business\video\agents\video.casting\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.channelmanager\docs\user_guide.script.hk.txt -o business\video\agents\video.channelmanager\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.childrensauthor\docs\user_guide.script.hk.txt -o business\video\agents\video.childrensauthor\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.choreography\docs\user_guide.script.hk.txt -o business\video\agents\video.choreography\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.cinematographer\docs\user_guide.script.hk.txt -o business\video\agents\video.cinematographer\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.citation\docs\user_guide.script.hk.txt -o business\video\agents\video.citation\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.colorist\docs\user_guide.script.hk.txt -o business\video\agents\video.colorist\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.comedywriter\docs\user_guide.script.hk.txt -o business\video\agents\video.comedywriter\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.comms\docs\user_guide.script.hk.txt -o business\video\agents\video.comms\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.community\docs\user_guide.script.hk.txt -o business\video\agents\video.community\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.competitorintelligence\docs\user_guide.script.hk.txt -o business\video\agents\video.competitorintelligence\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.compliance\docs\user_guide.script.hk.txt -o business\video\agents\video.compliance\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.composer\docs\user_guide.script.hk.txt -o business\video\agents\video.composer\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.conceptartist\docs\user_guide.script.hk.txt -o business\video\agents\video.conceptartist\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.continuity\docs\user_guide.script.hk.txt -o business\video\agents\video.continuity\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.copywriter\docs\user_guide.script.hk.txt -o business\video\agents\video.copywriter\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.corrections\docs\user_guide.script.hk.txt -o business\video\agents\video.corrections\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.costoptimizer\docs\user_guide.script.hk.txt -o business\video\agents\video.costoptimizer\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.costumedesign\docs\user_guide.script.hk.txt -o business\video\agents\video.costumedesign\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.creativedirector\docs\user_guide.script.hk.txt -o business\video\agents\video.creativedirector\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.critic\docs\user_guide.script.hk.txt -o business\video\agents\video.critic\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.crm\docs\user_guide.script.hk.txt -o business\video\agents\video.crm\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.deepfakedetection\docs\user_guide.script.hk.txt -o business\video\agents\video.deepfakedetection\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.director\docs\user_guide.script.hk.txt -o business\video\agents\video.director\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.distributor\docs\user_guide.script.hk.txt -o business\video\agents\video.distributor\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.dronepilot\docs\user_guide.script.hk.txt -o business\video\agents\video.dronepilot\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.editor\docs\user_guide.script.hk.txt -o business\video\agents\video.editor\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.emotionalarc\docs\user_guide.script.hk.txt -o business\video\agents\video.emotionalarc\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.ethics\docs\user_guide.script.hk.txt -o business\video\agents\video.ethics\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.evaluationharness\docs\user_guide.script.hk.txt -o business\video\agents\video.evaluationharness\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.factchecker\docs\user_guide.script.hk.txt -o business\video\agents\video.factchecker\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.festivalstrategist\docs\user_guide.script.hk.txt -o business\video\agents\video.festivalstrategist\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.finance\docs\user_guide.script.hk.txt -o business\video\agents\video.finance\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.foodstylist\docs\user_guide.script.hk.txt -o business\video\agents\video.foodstylist\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.gatekeeper\docs\user_guide.script.hk.txt -o business\video\agents\video.gatekeeper\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.ideation\docs\user_guide.script.hk.txt -o business\video\agents\video.ideation\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.instructionaldesign\docs\user_guide.script.hk.txt -o business\video\agents\video.instructionaldesign\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.interviewsynthesis\docs\user_guide.script.hk.txt -o business\video\agents\video.interviewsynthesis\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.journalist\docs\user_guide.script.hk.txt -o business\video\agents\video.journalist\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.judge\docs\user_guide.script.hk.txt -o business\video\agents\video.judge\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.labela_r\docs\user_guide.script.hk.txt -o business\video\agents\video.labela_r\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.labeldigital\docs\user_guide.script.hk.txt -o business\video\agents\video.labeldigital\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.latencyoptimizer\docs\user_guide.script.hk.txt -o business\video\agents\video.latencyoptimizer\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.learnersim\docs\user_guide.script.hk.txt -o business\video\agents\video.learnersim\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.legal\docs\user_guide.script.hk.txt -o business\video\agents\video.legal\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.lipsync\docs\user_guide.script.hk.txt -o business\video\agents\video.lipsync\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.lms\docs\user_guide.script.hk.txt -o business\video\agents\video.lms\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.localizationqa\docs\user_guide.script.hk.txt -o business\video\agents\video.localizationqa\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.marketing\docs\user_guide.script.hk.txt -o business\video\agents\video.marketing\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.medicalillustrator\docs\user_guide.script.hk.txt -o business\video\agents\video.medicalillustrator\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.memory\docs\user_guide.script.hk.txt -o business\video\agents\video.memory\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.moodboard\docs\user_guide.script.hk.txt -o business\video\agents\video.moodboard\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.motiongraphics\docs\user_guide.script.hk.txt -o business\video\agents\video.motiongraphics\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.mpa\docs\user_guide.script.hk.txt -o business\video\agents\video.mpa\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.mua_makeup\docs\user_guide.script.hk.txt -o business\video\agents\video.mua_makeup\docs\user_guide.script.hk.mp3
python tts.py business\video\agents\video.musicsupervisor\docs\user_guide.script.hk.txt -o business\video\agents\video.musicsupervisor\docs\user_guide.script.hk.mp3
