import Link from "next/link";

import { COMMON_AGENTS } from "../lib/demo-data";
import { PageHeader, StatusBadge, VersionPill } from "./design";

export function AgentDetail({ agentId }: { readonly agentId: string }): JSX.Element | null {
  const agent = COMMON_AGENTS.find((item) => item.id === agentId) ?? COMMON_AGENTS[1];
  if (!agent) return null;
  return <><Link className="back-link" href="/registry">← Back to Common Registry</Link><PageHeader eyebrow="COMMON AGENT" title={agent.name} description={agent.description} actions={<div className="button-row"><button className="button button--secondary" type="button">Fork to custom</button><button className="button button--primary" type="button">Propose improvement</button></div>} /><section className="agent-summary"><div><VersionPill version={agent.version} /><p>Active · last improved 3 days ago</p></div><dl><div><dt>Global runs</dt><dd>12.4k</dd></div><div><dt>Success rate</dt><dd>{agent.successRate}</dd></div><div><dt>Avg. tokens</dt><dd>2.8k</dd></div><div><dt>Active swarms</dt><dd>{agent.usage}</dd></div></dl></section><section className="detail-layout"><div><nav className="tabs" aria-label="Agent detail tabs"><button className="active" type="button">History & usage</button><button type="button">Configuration</button><button type="button">Playground</button><button type="button">Knowledge</button><button type="button">Ops & rollout</button></nav><article className="panel"><div className="panel-heading"><div><p className="eyebrow">CROSS-SWARM USAGE</p><h2>Healthy where it matters</h2></div><button className="filter-button" type="button">All swarms ⌄</button></div><div className="usage-insight"><strong>96%</strong><p>success in your usage, outperforming the global 91.4% baseline across 8 active swarms.</p></div><div className="run-table" role="table" aria-label="Agent usage"><div className="run-table__head" role="row"><span>SWARM</span><span>PATTERN</span><span>VERSION</span><span>STATUS</span><span>METRICS</span></div><div className="run-table__row" role="row"><span>Daily market brief</span><span>Parallel + verification</span><VersionPill version={agent.version} /><StatusBadge status="success" /><span>1.2s · $0.08</span></div><div className="run-table__row" role="row"><span>Research digest</span><span>Supervisor + specialists</span><VersionPill version={agent.version} /><StatusBadge status="running" /><span>Running · $0.12</span></div></div></article></div><aside className="panel detail-aside"><p className="eyebrow">SAFE ROLLOUT</p><h2>v{agent.version} is recommended</h2><p>The current version improved groundedness by 9% after adding a source-check stage.</p><div className="impact-stats"><span><b>19</b> swarms affected</span><span><b>+15%</b> expected latency gain</span></div><button className="button button--primary button--wide" type="button">Review rollout</button><Link className="button button--ghost button--wide" href="/canvas">Test in canvas</Link></aside></section></>;
}
