import test from 'node:test';
import assert from 'node:assert/strict';
import { plan as kiroPlan } from '../scripts/adapters/kiro.mjs';
import { plan as claudePlan } from '../scripts/adapters/claude-code.mjs';
import { allowedOutput } from '../scripts/lib/fs-safe.mjs';
import { readdir } from 'node:fs/promises';
const inputs = { rules: [{ name: 'rule.md', content: '# Rule' }], skills: [{ id: 'test', content: '# Skill' }], hooks: [{ id: 'gate', event: 'preCommit', command: 'npm run sdd:check' }], mcp: { mcpServers: {} } };
test('adapters plan only allowlisted files with managed headers', async () => {
  const kiroFiles = await kiroPlan(inputs);
  assert.ok(kiroFiles.has('.kiro/skills/test/SKILL.md'));
  for (const plan of [kiroFiles, await claudePlan(inputs)]) for (const [file, content] of plan) { assert.ok(allowedOutput(file), file); assert.match(content, /AUTO-GENERATED by CASOPS/); }
});
test('only the two supported adapters are present', async () => {
  assert.deepEqual((await readdir('scripts/adapters')).sort(), ['claude-code.mjs', 'kiro.mjs']);
});
