/* AUTO-GENERATED by scripts/business/export_pack_process_for_ui.py — do not edit. */
/* Host process index + design catalog counts for Registry/Blueprints presentation. */
/* production_ready remains false; browser is non-authority. */

export interface PackProcessRow {
  readonly processId: string;
  readonly workflowPath: string;
  readonly status: string;
  readonly agentCount: number;
}

export interface PackProcessCatalog {
  readonly hostProcessCount: number;
  readonly designProcessCount: number;
  readonly dnaWorkflowCount: number;
  readonly graphCount: number;
  readonly evalArtifactCount: number;
  readonly productionReady: false;
  readonly safeBaseline: string;
  readonly processes: readonly PackProcessRow[];
  readonly dnaWorkflows: readonly string[];
  readonly graphs: readonly string[];
  readonly evalArtifacts: readonly string[];
}

export const PACK_PROCESS_CATALOG: PackProcessCatalog = {
  "hostProcessCount": 27,
  "designProcessCount": 33,
  "dnaWorkflowCount": 14,
  "graphCount": 2,
  "evalArtifactCount": 5,
  "productionReady": false,
  "safeBaseline": "workflows/pack_spine.json",
  "processes": [
    {
      "processId": "video.spine.orchestrate",
      "workflowPath": "workflows/wf_video_spine_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 7
    },
    {
      "processId": "video.spine.plan",
      "workflowPath": "workflows/wf_video_spine_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 7
    },
    {
      "processId": "video.phase.1.intent_planning",
      "workflowPath": "workflows/wf_video_production_e2e_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 9
    },
    {
      "processId": "video.phase.2.creative",
      "workflowPath": "workflows/wf_video_production_e2e_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 9
    },
    {
      "processId": "video.phase.3.prepro",
      "workflowPath": "workflows/wf_video_production_e2e_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 9
    },
    {
      "processId": "video.phase.4.production",
      "workflowPath": "workflows/wf_video_production_e2e_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 9
    },
    {
      "processId": "video.phase.5.post",
      "workflowPath": "workflows/wf_video_production_e2e_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 9
    },
    {
      "processId": "video.phase.6.delivery",
      "workflowPath": "workflows/wf_video_production_e2e_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 9
    },
    {
      "processId": "video.arch.a.viral_hook",
      "workflowPath": "workflows/wf_video_arch_a_viral_hook_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 6
    },
    {
      "processId": "video.arch.b.ugc_ad",
      "workflowPath": "workflows/wf_video_arch_b_ugc_ad_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 10
    },
    {
      "processId": "video.arch.c.animated_explainer",
      "workflowPath": "workflows/wf_video_arch_c_animated_explainer_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 7
    },
    {
      "processId": "video.arch.d.personalized_birthday",
      "workflowPath": "workflows/wf_video_arch_d_personalized_birthday_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 5
    },
    {
      "processId": "video.arch.e.ai_short_film",
      "workflowPath": "workflows/wf_video_arch_e_ai_short_film_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 12
    },
    {
      "processId": "video.arch.f.corporate_training",
      "workflowPath": "workflows/wf_video_arch_f_corporate_training_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 6
    },
    {
      "processId": "video.arch.g.music_video",
      "workflowPath": "workflows/wf_video_arch_g_music_video_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 5
    },
    {
      "processId": "video.arch.h.ai_avatar",
      "workflowPath": "workflows/wf_video_arch_h_ai_avatar_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 7
    },
    {
      "processId": "video.arch.i.documentary",
      "workflowPath": "workflows/wf_video_arch_i_documentary_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 7
    },
    {
      "processId": "video.arch.j.feature_film",
      "workflowPath": "workflows/wf_video_arch_j_feature_film_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 8
    },
    {
      "processId": "video.lqr.overview",
      "workflowPath": "workflows/wf_video_lqr_overview_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 5
    },
    {
      "processId": "video.lqr.scene_flow",
      "workflowPath": "workflows/wf_video_lqr_overview_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 5
    },
    {
      "processId": "video.lqr.per_shot_loop",
      "workflowPath": "workflows/wf_video_lqr_overview_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 5
    },
    {
      "processId": "video.lqr.character_consistency",
      "workflowPath": "workflows/wf_video_lqr_overview_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 5
    },
    {
      "processId": "video.lqr.engine_routing",
      "workflowPath": "workflows/wf_video_lqr_overview_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 5
    },
    {
      "processId": "video.lqr.quality_gates",
      "workflowPath": "workflows/wf_video_lqr_overview_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 5
    },
    {
      "processId": "video.qc.critique_bus",
      "workflowPath": "workflows/wf_video_lqr_overview_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 5
    },
    {
      "processId": "video.qc.consistency",
      "workflowPath": "workflows/wf_video_lqr_overview_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 5
    },
    {
      "processId": "video.delivery.package",
      "workflowPath": "workflows/wf_video_delivery_v1.dna.json",
      "status": "adapted_host_graph",
      "agentCount": 6
    }
  ],
  "dnaWorkflows": [
    "wf_video_arch_a_viral_hook_v1.dna.json",
    "wf_video_arch_b_ugc_ad_v1.dna.json",
    "wf_video_arch_c_animated_explainer_v1.dna.json",
    "wf_video_arch_d_personalized_birthday_v1.dna.json",
    "wf_video_arch_e_ai_short_film_v1.dna.json",
    "wf_video_arch_f_corporate_training_v1.dna.json",
    "wf_video_arch_g_music_video_v1.dna.json",
    "wf_video_arch_h_ai_avatar_v1.dna.json",
    "wf_video_arch_i_documentary_v1.dna.json",
    "wf_video_arch_j_feature_film_v1.dna.json",
    "wf_video_delivery_v1.dna.json",
    "wf_video_lqr_overview_v1.dna.json",
    "wf_video_production_e2e_v1.dna.json",
    "wf_video_spine_v1.dna.json"
  ],
  "graphs": [
    "video_spine.graph.json",
    "viral_hook.graph.json"
  ],
  "evalArtifacts": [
    "adversarial/video-tool-misuse-injection.json",
    "golden/.gitkeep",
    "golden/video-lqr-consistency.json",
    "golden/video-spine-viral-hook.json",
    "rubrics/lqr-consistency.md"
  ]
} as const;
