import { access, mkdir, readFile, writeFile, lstat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
export const prohibitedPattern = /\bgemini(?:\s+cli|-cli)?\b/i;
export const outputAllowlist = ['.kiro/settings.json', '.kiro/mcp.json', '.kiro/steering/', '.kiro/hooks/', '.kiro/skills/', 'CLAUDE.md', '.claude/settings.json', '.claude/skills/', '.claude/commands/', '.claude/agents/'];
export function confined(relative) {
  if (!relative || path.isAbsolute(relative)) throw new Error(`Unsafe path: ${relative}`);
  const resolved = path.resolve(root, relative);
  if (resolved !== root && !resolved.startsWith(`${root}${path.sep}`)) throw new Error(`Path escapes project root: ${relative}`);
  return resolved;
}
export function allowedOutput(relative) { return outputAllowlist.some(entry => entry.endsWith('/') ? relative.startsWith(entry) : relative === entry); }
export async function readJson(relative) { return JSON.parse(await readFile(confined(relative), 'utf8')); }
export async function writeText(relative, text) { const file = confined(relative); await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, text, 'utf8'); }
export async function exists(relative) { try { await access(confined(relative)); return true; } catch { return false; } }
export async function isSymlink(relative) { try { return (await lstat(confined(relative))).isSymbolicLink(); } catch { return false; } }
export function stable(value) { return `${JSON.stringify(value, null, 2)}\n`; }
export function assertNoProhibited(value, label = 'input') { if (prohibitedPattern.test(typeof value === 'string' ? value : JSON.stringify(value))) throw new Error(`Prohibited source reference in ${label}`); }
export function managedMarkdown(content) { return `<!-- AUTO-GENERATED by CASOPS. Do not edit directly.\nSource: rules/, skills/, hooks/, mcp-configs/\nRun: npm run sync\n-->\n<!-- BEGIN CASOPS MANAGED CONTENT -->\n${content.trim()}\n<!-- END CASOPS MANAGED CONTENT -->\n`; }
export function managedJson(value) { return stable({ _casops: 'AUTO-GENERATED by CASOPS; run npm run sync', ...value }); }
