"""Offline agentic pipeline: analyze → plan → retrieve → grade → generate → critic.

Implements lite versions of the 4 core patterns and iterative reflection
without LangGraph/LangSmith/live LLM.
"""

from __future__ import annotations

import re
from typing import Any
from uuid import uuid4

from app.rag.index import LocalDocumentIndex
from app.rag.models import ACTIVATION_POLICY

_TOKEN = re.compile(r"[a-z0-9]+", re.I)

_RELATIONAL_HINTS = (
    "compare",
    "relation",
    "related",
    "who",
    "connected",
    "depend",
    "between",
    "versus",
    "vs",
    "how does",
    "which",
    "multi-hop",
    "across",
)
_MULTI_HOP_HINTS = (
    "and then",
    "also",
    "both",
    "step",
    "pipeline",
    "workflow",
    "how to",
    "explain",
    "difference",
)


def _tokens(text: str) -> set[str]:
    return {t.lower() for t in _TOKEN.findall(text or "") if len(t) > 1}


def analyze_query(query: str) -> dict[str, Any]:
    q = (query or "").strip().lower()
    if any(h in q for h in _RELATIONAL_HINTS):
        complexity = "relational"
        strategy = "hybrid_lite"
    elif any(h in q for h in _MULTI_HOP_HINTS) or q.count("?") > 1 or " and " in q:
        complexity = "multi_hop"
        strategy = "vector_lite"
    else:
        complexity = "simple"
        strategy = "vector_lite"
    return {
        "complexity": complexity,
        "strategy": strategy,
        "requires_relationships": complexity == "relational",
        "node": "query_analyzer",
    }


def plan_query(query: str, *, complexity: str) -> list[str]:
    q = (query or "").strip()
    if complexity == "simple":
        return [f"Retrieve evidence for: {q}", "Synthesize grounded answer with citations"]
    if complexity == "relational":
        return [
            f"Identify entities and relations in: {q}",
            "Retrieve relationship-aware chunks",
            "Cross-check multi-hop evidence",
            "Synthesize answer with provenance",
        ]
    # multi_hop
    parts = re.split(r"\band\b|\bthen\b|;", q, flags=re.I)
    sub = [p.strip() for p in parts if p.strip()][:4]
    if len(sub) < 2:
        sub = [q, f"Supporting context for: {q}"]
    plan = [f"Sub-query: {s}" for s in sub]
    plan.append("Merge evidence and cite sources")
    return plan


def grade_chunk(query: str, chunk: dict[str, Any]) -> float:
    q = _tokens(query)
    c = _tokens(str(chunk.get("content") or "") + " " + str(chunk.get("title") or ""))
    if not q or not c:
        return 0.0
    overlap = len(q & c)
    coverage = overlap / max(1, len(q))
    base = float(chunk.get("relevance_score") or 0.0)
    grade = 0.5 * base + 0.5 * min(1.0, coverage * 1.2)
    # Authority/recency stubs: host:// sources slightly preferred
    src = str(chunk.get("source_ref") or "")
    if src.startswith("host://"):
        grade = min(1.0, grade + 0.04)
    return round(max(0.0, min(1.0, grade)), 4)


def generate_answer(
    query: str,
    graded: list[dict[str, Any]],
    *,
    plan: list[str],
) -> dict[str, Any]:
    if not graded:
        return {
            "final_answer": (
                f"No grounded evidence found for: {query}. "
                "Ingest more local documents or refine the query. "
                "(Offline index only — live web/LightRAG disabled.)"
            ),
            "citations": [],
            "confidence": 0.05,
        }

    lines = [
        f"**Query:** {query}",
        "",
        "**Answer (offline grounded):**",
    ]
    # Build from top graded excerpts
    for i, doc in enumerate(graded[:5], start=1):
        excerpt = str(doc.get("content") or "").strip().replace("\n", " ")
        if len(excerpt) > 280:
            excerpt = excerpt[:277] + "..."
        lines.append(f"{i}. {excerpt}")
        lines.append(f"   — _{doc.get('title')}_ (`{doc.get('source_ref')}`)")
    lines.extend(
        [
            "",
            "**Plan executed:**",
            *[f"- {p}" for p in plan[:6]],
            "",
            "_Generated by offline Host Agentic RAG foundation (not production hybrid RAG)._",
        ]
    )
    citations = []
    for doc in graded[:8]:
        excerpt = str(doc.get("content") or "").strip().replace("\n", " ")
        citations.append(
            {
                "chunk_id": doc.get("chunk_id"),
                "source_ref": doc.get("source_ref"),
                "title": doc.get("title"),
                "excerpt": (excerpt[:200] + "...") if len(excerpt) > 200 else excerpt,
                "score": float(doc.get("grade") or doc.get("relevance_score") or 0.0),
            }
        )
    conf = sum(float(d.get("grade") or 0.0) for d in graded[:5]) / max(1, min(5, len(graded)))
    return {
        "final_answer": "\n".join(lines),
        "citations": citations,
        "confidence": round(min(0.95, conf), 4),
    }


def critic_score(answer: str, graded: list[dict[str, Any]]) -> dict[str, Any]:
    """Heuristic faithfulness: answer tokens should overlap retrieved evidence."""
    a = _tokens(answer)
    if not graded:
        return {
            "faithfulness": 0.0,
            "pass": False,
            "critique": "No evidence — cannot validate faithfulness.",
        }
    evidence = set()
    for d in graded:
        evidence |= _tokens(str(d.get("content") or ""))
    if not a:
        return {"faithfulness": 0.0, "pass": False, "critique": "Empty answer."}
    # Exclude boilerplate words
    boilerplate = {
        "query",
        "answer",
        "offline",
        "grounded",
        "plan",
        "executed",
        "generated",
        "host",
        "agentic",
        "foundation",
        "production",
        "hybrid",
        "rag",
    }
    content_tokens = a - boilerplate
    if not content_tokens:
        content_tokens = a
    overlap = len(content_tokens & evidence)
    faith = overlap / max(1, len(content_tokens))
    # Cap when few sources
    faith = min(1.0, faith * 1.15)
    ok = faith >= 0.35 and len(graded) >= 1
    critique = (
        f"Faithfulness≈{faith:.2f} over {len(graded)} docs; "
        + ("pass." if ok else "below threshold — reflect/retrieve again.")
    )
    return {
        "faithfulness": round(faith, 4),
        "pass": ok,
        "critique": critique,
    }


def run_agentic_query(
    index: LocalDocumentIndex,
    *,
    query: str,
    max_iterations: int = 3,
    top_k: int = 8,
    require_relationships: bool | None = None,
) -> dict[str, Any]:
    """Execute offline agentic loop with reflection (max 3 iterations)."""
    run_id = f"rag_run_{uuid4().hex[:12]}"
    trace: list[dict[str, Any]] = []
    analysis = analyze_query(query)
    if require_relationships is True:
        analysis["requires_relationships"] = True
        analysis["complexity"] = "relational"
        analysis["strategy"] = "hybrid_lite"
    elif require_relationships is False:
        analysis["requires_relationships"] = False

    plan = plan_query(query, complexity=str(analysis["complexity"]))
    trace.append({"node": "query_analyzer", **analysis})
    trace.append({"node": "planner", "plan": plan})

    patterns = ["Planning", "Tool Use"]
    elements = [
        "single_agent_routing",
        "adaptive_retrieval",
        "stateful_memory_lite",
        "hybrid_knowledge_lite",
        "iterative_refinement",
        "evaluation_aware_trace",
    ]
    reflection_triggered = False
    graded: list[dict[str, Any]] = []
    retrieved: list[dict[str, Any]] = []
    answer_payload: dict[str, Any] = {}
    critique_info: dict[str, Any] = {}
    iteration = 0
    active_query = query

    for iteration in range(1, max_iterations + 1):
        # Tool use: local hybrid retrieve
        rel = bool(analysis["requires_relationships"]) or iteration > 1
        hits = index.search(
            active_query,
            top_k=top_k,
            relationship_boost=rel,
        )
        # Multi-hop: also search plan sub-queries
        if analysis["complexity"] in {"multi_hop", "relational"} and iteration == 1:
            for step in plan[:3]:
                sub_q = step.replace("Sub-query:", "").strip()
                extra = index.search(sub_q, top_k=max(2, top_k // 2), relationship_boost=rel)
                hits.extend(extra)
        # Dedup by chunk_id
        by_id: dict[str, dict[str, Any]] = {}
        for h in hits:
            cid = str(h.get("chunk_id"))
            prev = by_id.get(cid)
            if prev is None or float(h.get("relevance_score") or 0) > float(
                prev.get("relevance_score") or 0
            ):
                by_id[cid] = h
        retrieved = sorted(
            by_id.values(),
            key=lambda r: float(r.get("relevance_score") or 0),
            reverse=True,
        )[:top_k]
        trace.append(
            {
                "node": "researcher",
                "iteration": iteration,
                "query": active_query,
                "hit_count": len(retrieved),
                "tool": "local_hierarchical_retrieve",
            }
        )
        patterns = list(dict.fromkeys(patterns + ["Tool Use"]))

        graded = []
        for h in retrieved:
            g = grade_chunk(active_query, h)
            row = {**h, "grade": g}
            if g >= 0.28:  # offline threshold (stub; prod would be ~0.75)
                graded.append(row)
        graded.sort(key=lambda r: r["grade"], reverse=True)
        trace.append(
            {
                "node": "grader",
                "iteration": iteration,
                "kept": len(graded),
                "threshold": 0.28,
            }
        )
        patterns = list(dict.fromkeys(patterns + ["Reflection"]))

        answer_payload = generate_answer(active_query, graded, plan=plan)
        critique_info = critic_score(
            str(answer_payload.get("final_answer") or ""), graded
        )
        trace.append(
            {
                "node": "generator",
                "iteration": iteration,
                "confidence": answer_payload.get("confidence"),
            }
        )
        trace.append(
            {
                "node": "critic",
                "iteration": iteration,
                **critique_info,
            }
        )
        patterns = list(dict.fromkeys(patterns + ["Multi-Agent Collaboration"]))

        if critique_info.get("pass") and float(answer_payload.get("confidence") or 0) >= 0.35:
            break
        if iteration < max_iterations:
            reflection_triggered = True
            # Reflect: broaden query with failing intent
            active_query = f"{query} evidence background context"
            plan = plan + [f"Reflection iter {iteration}: broaden retrieve"]
            trace.append(
                {
                    "node": "reflection_loop",
                    "iteration": iteration,
                    "action": "broaden_query_and_retry",
                }
            )

    conf = float(answer_payload.get("confidence") or 0.0)
    faith = float(critique_info.get("faithfulness") or 0.0)
    escalate = conf < 0.25 or faith < 0.25 or not graded

    return {
        "run_id": run_id,
        "query": query,
        "complexity": analysis["complexity"],
        "strategy": analysis["strategy"],
        "plan": plan,
        "iterations": iteration,
        "confidence": conf,
        "retrieved": retrieved,
        "graded_docs": graded,
        "critique": critique_info.get("critique") or "",
        "final_answer": answer_payload.get("final_answer") or "",
        "citations": answer_payload.get("citations") or [],
        "patterns_used": patterns,
        "elements_used": elements,
        "reflection_triggered": reflection_triggered,
        "escalate_to_hitl": escalate,
        "activation_policy": dict(ACTIVATION_POLICY),
        "note": (
            "Offline deterministic Agentic RAG foundation. "
            "Not Chroma/LightRAG/Tavily production stack."
        ),
        "trace": trace,
        "ok": True,
    }
