import { exists, readJson, writeText } from './lib/fs-safe.mjs';
import { loadManifests } from './lib/manifest.mjs';
const { sources } = await loadManifests();
const lock = await exists('sources/source-lock.json') ? await readJson('sources/source-lock.json') : { sources: [], failures: [] };
const byId = new Map(lock.sources.map(entry => [entry.id, entry]));
const lines = ['# Source Audit', '', 'Generated by `npm run sources:audit`. Downloaded material remains untrusted and is never executed.', '', '## Policy', '', 'Cross-agent references may inform manual curation but cannot produce native output for other tools. Gemini and Gemini CLI materials are prohibited and rejected without download or audit.', ''];
for (const source of sources.sources) { const entry = byId.get(source.id) || {}; const rejected = source.priority === 'archived' ? 'archived source; automatic import rejected' : 'bulk import rejected until human review';
  lines.push(`## ${source.name}`, '', `- URL: ${source.url}`, `- Target: ${source.target}`, `- Status: ${entry.status || (source.enabled ? 'not downloaded' : 'disabled')}`, `- Commit: ${entry.commit || 'none'}`, `- Branch: ${entry.branch || 'none'}`, `- License files: ${(entry.license_files || []).join(', ') || 'none found'}`, `- Package files: ${(entry.package_files || []).join(', ') || 'none found'}`, `- Priority / tier: ${source.priority} / ${source.tier}`, `- Quarantine: ${source.quarantine}`, `- Import policy: ${source.import_policy}`, `- Purpose: ${source.purpose}`, '- Selected components: none yet', `- Rejected components: ${rejected}`, '- Security notes: license, install behavior, credentials, global changes, and MCP scope require review.', ''); }
if (lock.failures?.length) lines.push('## Failures', '', ...lock.failures.map(f => `- ${f.id}: ${f.error}`), '');
await writeText('docs/source-audit.md', `${lines.join('\n')}\n`); console.log('Source audit: written');
