#!/usr/bin/env python3
"""Export video process_coverage + pack trees into a frontend projection module."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
VIDEO = ROOT / "business" / "video"
OUT = ROOT / "frontend" / "src" / "lib" / "projections" / "pack-process.generated.ts"


def main() -> int:
    host = json.loads((VIDEO / "process_coverage.json").read_text(encoding="utf-8"))
    design_path = VIDEO / "design" / "process_coverage_va.json"
    design = (
        json.loads(design_path.read_text(encoding="utf-8"))
        if design_path.is_file()
        else {"processes": []}
    )
    host_processes = host.get("processes") if isinstance(host, dict) else []
    design_processes = design.get("processes") if isinstance(design, dict) else []
    if not isinstance(host_processes, list):
        host_processes = []
    if not isinstance(design_processes, list):
        design_processes = []

    dna = sorted(p.name for p in (VIDEO / "workflows").glob("*.dna.json"))
    graphs = sorted(p.name for p in (VIDEO / "graphs").glob("*.json")) if (VIDEO / "graphs").is_dir() else []
    eval_files = (
        sorted(p.relative_to(VIDEO / "evals").as_posix() for p in (VIDEO / "evals").rglob("*") if p.is_file())
        if (VIDEO / "evals").is_dir()
        else []
    )

    rows = []
    for p in host_processes:
        if not isinstance(p, dict):
            continue
        rows.append(
            {
                "processId": str(p.get("process_id") or ""),
                "workflowPath": str(p.get("workflow_path") or p.get("path") or ""),
                "status": str(p.get("status") or ""),
                "agentCount": len(p.get("agent_ids") or [])
                if isinstance(p.get("agent_ids"), list)
                else 0,
            }
        )

    payload = {
        "hostProcessCount": len(rows),
        "designProcessCount": len(design_processes),
        "dnaWorkflowCount": len(dna),
        "graphCount": len(graphs),
        "evalArtifactCount": len(eval_files),
        "productionReady": False,
        "safeBaseline": "workflows/pack_spine.json",
        "processes": rows,
        "dnaWorkflows": dna,
        "graphs": graphs,
        "evalArtifacts": eval_files,
    }

    body = (
        "/* AUTO-GENERATED by scripts/business/export_pack_process_for_ui.py — do not edit. */\n"
        "/* Host process index + design catalog counts for Registry/Blueprints presentation. */\n"
        "/* production_ready remains false; browser is non-authority. */\n\n"
        "export interface PackProcessRow {\n"
        "  readonly processId: string;\n"
        "  readonly workflowPath: string;\n"
        "  readonly status: string;\n"
        "  readonly agentCount: number;\n"
        "}\n\n"
        "export interface PackProcessCatalog {\n"
        "  readonly hostProcessCount: number;\n"
        "  readonly designProcessCount: number;\n"
        "  readonly dnaWorkflowCount: number;\n"
        "  readonly graphCount: number;\n"
        "  readonly evalArtifactCount: number;\n"
        "  readonly productionReady: false;\n"
        "  readonly safeBaseline: string;\n"
        "  readonly processes: readonly PackProcessRow[];\n"
        "  readonly dnaWorkflows: readonly string[];\n"
        "  readonly graphs: readonly string[];\n"
        "  readonly evalArtifacts: readonly string[];\n"
        "}\n\n"
        f"export const PACK_PROCESS_CATALOG: PackProcessCatalog = {json.dumps(payload, indent=2)} as const;\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(
        json.dumps(
            {
                "out": str(OUT.relative_to(ROOT)),
                "host": payload["hostProcessCount"],
                "design": payload["designProcessCount"],
                "dna": payload["dnaWorkflowCount"],
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
